spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        format_sql: true
        default_batch_fetch_size: 20
    open-in-view: false

  datasource:
    url: jdbc:h2:mem:computerstore
#    tcp: jdbc:h2:tcp://localhost:9092/mem:computerstore
    username: sa
    password:

  liquibase:
    change-log: "classpath:db/changelog.sql"

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cache: TRACE
    liquibase: DEBUG

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8081

springdoc.swagger-ui.path: /
